// Snapshot of roundtrip-verify results (Sprint 216, 2026-04-20)
// Generated by: npx tsx scripts/roundtrip-verify/index.ts --json

export const phase2Metrics = {
  implementedRate: 91.7,
  implementedPassed: 11,
  implementedTotal: 12,
  overallRate: 39.3,
  total: 28,
  unsupportedCount: 16,
  generatedAt: "2026-04-20T06:50:17.530Z",
  kpiMet: true,
  kpiThreshold: 90,
};

export const trackAFill = [
  { service: "lpon-budget",    label: "예산 관리",  implemented: false, fillPercent: 100 },
  { service: "lpon-charge",    label: "충전",       implemented: false, fillPercent: 100 },
  { service: "lpon-purchase",  label: "구매",       implemented: false, fillPercent: 100 },
  { service: "lpon-payment",   label: "결제",       implemented: true,  fillPercent: 100 },
  { service: "lpon-refund",    label: "환불",       implemented: true,  fillPercent: 100 },
  { service: "lpon-gift",      label: "선물",       implemented: false, fillPercent: 100 },
  { service: "lpon-settlement",label: "정산",       implemented: false, fillPercent: 100 },
];

export interface ScenarioResult {
  contractFile: string;
  scenarioId: string;
  scenarioName: string;
  passed: boolean;
  failReason?: string;
  failDetail?: string;
}

export const scenarioResults: ScenarioResult[] = [
  { contractFile: "lpon-payment", scenarioId: "TC-PAYMENT-001", scenarioName: "잔액 충분 + 활성 가맹점 → 결제 성공", passed: true },
  { contractFile: "lpon-payment", scenarioId: "TC-PAYMENT-002", scenarioName: "잔액 부족 → 결제 거부", passed: true },
  { contractFile: "lpon-payment", scenarioId: "TC-PAYMENT-003", scenarioName: "비활성 가맹점 → 결제 거부", passed: true },
  { contractFile: "lpon-payment", scenarioId: "TC-PAYMENT-004", scenarioName: "50,000원 이상 결제 시 SMS 발송", passed: true },
  { contractFile: "lpon-payment", scenarioId: "TC-PAYMENT-005", scenarioName: "CARD 결제 — 카드사 승인 성공", passed: true },
  { contractFile: "lpon-payment", scenarioId: "TC-PAYMENT-006", scenarioName: "FULL 결제취소 — 잔액 복구", passed: true },
  { contractFile: "lpon-refund",  scenarioId: "TC-REFUND-001",  scenarioName: "rfndPsbltyYn=Y + UNUSED_FULL + 7일 이내 → 환불 신청 성공", passed: true },
  {
    contractFile: "lpon-refund",  scenarioId: "TC-REFUND-002",  scenarioName: "UNUSED_FULL + 7일 초과 → 환불 거부",
    passed: false, failReason: "WRONG_OUTCOME",
    failDetail: "BL-024(UNUSED_FULL 7일 이내 제한) 미구현 — domain이 기간 체크 없이 항상 REQUESTED 반환",
  },
  { contractFile: "lpon-refund",  scenarioId: "TC-REFUND-003",  scenarioName: "USED_BALANCE + 60% 이상 사용 → 잔액 환불 가능", passed: true },
  { contractFile: "lpon-refund",  scenarioId: "TC-REFUND-004",  scenarioName: "환불 승인 → 입금 처리", passed: true },
  { contractFile: "lpon-refund",  scenarioId: "TC-REFUND-005",  scenarioName: "환불 거절 → status=REJECTED", passed: true },
  { contractFile: "lpon-refund",  scenarioId: "TC-REFUND-006",  scenarioName: "제외금액 산정 후 입금액 계산", passed: true },
];

export const unsupportedDomains = [
  { domain: "lpon-budget",   label: "예산 관리", scenarios: 5,  reason: "Working Prototype 미구현 서비스" },
  { domain: "lpon-charge",   label: "충전",      scenarios: 6,  reason: "Working Prototype 미구현 서비스" },
  { domain: "lpon-purchase", label: "구매",      scenarios: 5,  reason: "Working Prototype 미구현 서비스" },
];

export const sourceFirstMarkers = {
  implemented: [
    { service: "lpon-payment", SOURCE_MISSING: 0, DOC_ONLY: 1, DIVERGENCE: 1, clean: 4 },
    { service: "lpon-refund",  SOURCE_MISSING: 1, DOC_ONLY: 0, DIVERGENCE: 0, clean: 5 },
  ],
  summary: {
    SOURCE_MISSING: 1,
    DOC_ONLY: 1,
    DIVERGENCE: 1,
    total: 3,
  },
};
