/**
 * Markdown Renderer — SpecDocument → 단일 마크다운 문자열 변환
 */
import type { SpecDocument } from "./types.js";

export function renderSpecToMarkdown(doc: SpecDocument): string {
  const header = [
    `---`,
    `skillId: ${doc.skillId}`,
    `type: ${doc.type}`,
    `generatedAt: ${doc.generatedAt}`,
    `domain: ${doc.metadata.domain}`,
    `policyCount: ${doc.metadata.policyCount}`,
    `---`,
    "",
  ].join("\n");

  const sorted = [...doc.sections].sort((a, b) => a.order - b.order);
  const body = sorted.map((s) => s.content).join("\n\n---\n\n");

  const footer = [
    "",
    "---",
    "",
    `> Generated by Decode-X Spec Generator at ${doc.generatedAt}`,
    `> Skill: ${doc.skillId} | Domain: ${doc.metadata.domain} | Policies: ${doc.metadata.policyCount}`,
  ].join("\n");

  return `${header}\n${body}\n${footer}\n`;
}
