/**
 * Fact Check Report Generator — produces Markdown reports from
 * fact-check results and gaps.
 *
 * Part of v0.7.4 Pivot Phase 2-B Session 3.
 */

import type { FactCheckGap } from "@ai-foundry/types";

// ── Input type ────────────────────────────────────────────────────

export interface ReportInput {
  resultId: string;
  organizationId: string;
  totalSourceItems: number;
  totalDocItems: number;
  matchedItems: number;
  gapCount: number;
  coveragePct: number;
  gapsByType: Record<string, number>;
  gapsBySeverity: Record<string, number>;
  gaps: FactCheckGap[];
}

// ── Gap type / severity labels ────────────────────────────────────

const GAP_TYPE_LABELS: Record<string, string> = {
  SM: "Schema Mismatch",
  MC: "Missing Column",
  PM: "Parameter Mismatch",
  TM: "Type Mismatch",
  MID: "Missing in Document",
};

const SEVERITY_ORDER = ["HIGH", "MEDIUM", "LOW"] as const;

// ── Main ──────────────────────────────────────────────────────────

export function generateFactCheckReport(input: ReportInput): string {
  const lines: string[] = [];

  // Title
  lines.push(`# Fact Check Report — ${input.organizationId}`);
  lines.push("");
  lines.push(`> Result ID: \`${input.resultId}\``);
  lines.push(`> Generated: ${new Date().toISOString()}`);
  lines.push("");

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|------:|");
  lines.push(`| Source Items | ${input.totalSourceItems} |`);
  lines.push(`| Document Items | ${input.totalDocItems} |`);
  lines.push(`| Matched | ${input.matchedItems} |`);
  lines.push(`| Gaps Found | ${input.gapCount} |`);
  lines.push(`| Coverage | ${input.coveragePct.toFixed(1)}% |`);
  lines.push("");

  // Gap Distribution: type x severity matrix
  lines.push("## Gap Distribution");
  lines.push("");

  const allTypes = Object.keys(GAP_TYPE_LABELS);

  // Build a matrix header row
  lines.push(`| Type | ${SEVERITY_ORDER.join(" | ")} | Total |`);
  lines.push(`|------|${SEVERITY_ORDER.map(() => "------:").join("|")}|------:|`);

  for (const gapType of allTypes) {
    const typeLabel = GAP_TYPE_LABELS[gapType] ?? gapType;
    const counts = SEVERITY_ORDER.map((sev) => {
      return input.gaps.filter(
        (g) => g.gapType === gapType && g.severity === sev,
      ).length;
    });
    const total = counts.reduce((a, b) => a + b, 0);
    if (total === 0) continue; // skip empty rows
    lines.push(`| ${typeLabel} (${gapType}) | ${counts.join(" | ")} | ${total} |`);
  }

  // Totals row
  const severityTotals = SEVERITY_ORDER.map((sev) =>
    input.gaps.filter((g) => g.severity === sev).length,
  );
  lines.push(
    `| **Total** | ${severityTotals.join(" | ")} | ${input.gapCount} |`,
  );
  lines.push("");

  // Detailed gap lists by severity
  for (const severity of SEVERITY_ORDER) {
    const gapsForSev = input.gaps.filter((g) => g.severity === severity);
    if (gapsForSev.length === 0) continue;

    lines.push(`## ${severity} Severity Gaps (${gapsForSev.length})`);
    lines.push("");

    for (const gap of gapsForSev) {
      const typeLabel = GAP_TYPE_LABELS[gap.gapType] ?? gap.gapType;
      lines.push(`### ${typeLabel} — \`${gap.sourceItem}\``);
      lines.push("");
      lines.push(`- **Gap ID**: \`${gap.gapId}\``);
      lines.push(`- **Type**: ${gap.gapType}`);
      lines.push(`- **Description**: ${gap.description}`);
      if (gap.documentItem) {
        lines.push(`- **Document Item**: ${gap.documentItem}`);
      }
      if (gap.evidence) {
        lines.push(`- **Evidence**: ${gap.evidence}`);
      }
      lines.push(`- **Review Status**: ${gap.reviewStatus}`);
      if (gap.autoResolved) {
        lines.push(`- **Auto-resolved**: Yes`);
      }
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("*Generated by AI Foundry Fact Check Engine (v0.7.4)*");
  lines.push("");

  return lines.join("\n");
}
